services:
  - type: web
    name: cecop-postulaciones-api
    env: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8081
      - key: DB_URL
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
